<?php

namespace Database\Seeders;

use App\Models\Skill;
use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;

class SkillSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $skills = [
            // --- Technical Skills ---
            ['skill_name' => 'Python', 'category' => 'Programming Languages'],
            ['skill_name' => 'Java', 'category' => 'Programming Languages'],
            ['skill_name' => 'JavaScript', 'category' => 'Programming Languages'],
            ['skill_name' => 'PHP', 'category' => 'Programming Languages'],
            ['skill_name' => 'C++', 'category' => 'Programming Languages'],
            ['skill_name' => 'C#', 'category' => 'Programming Languages'],
            ['skill_name' => 'Go', 'category' => 'Programming Languages'],
            ['skill_name' => 'Ruby', 'category' => 'Programming Languages'],
            ['skill_name' => 'Swift', 'category' => 'Programming Languages'],
            ['skill_name' => 'Kotlin', 'category' => 'Programming Languages'],
            ['skill_name' => 'TypeScript', 'category' => 'Programming Languages'],
            ['skill_name' => 'SQL', 'category' => 'Database Management'],
            ['skill_name' => 'NoSQL', 'category' => 'Database Management'],
            ['skill_name' => 'MySQL', 'category' => 'Database Management'],
            ['skill_name' => 'PostgreSQL', 'category' => 'Database Management'],
            ['skill_name' => 'MongoDB', 'category' => 'Database Management'],
            ['skill_name' => 'Microsoft SQL Server', 'category' => 'Database Management'],
            ['skill_name' => 'Oracle Database', 'category' => 'Database Management'],
            ['skill_name' => 'Data Structures', 'category' => 'Computer Science Fundamentals'],
            ['skill_name' => 'Algorithms', 'category' => 'Computer Science Fundamentals'],
            ['skill_name' => 'Operating Systems', 'category' => 'Computer Science Fundamentals'],
            ['skill_name' => 'Networking', 'category' => 'Computer Science Fundamentals'],
            ['skill_name' => 'Linux', 'category' => 'Operating Systems'],
            ['skill_name' => 'Windows Server', 'category' => 'Operating Systems'],
            ['skill_name' => 'macOS', 'category' => 'Operating Systems'],
            ['skill_name' => 'React.js', 'category' => 'Frontend Frameworks'],
            ['skill_name' => 'Angular', 'category' => 'Frontend Frameworks'],
            ['skill_name' => 'Vue.js', 'category' => 'Frontend Frameworks'],
            ['skill_name' => 'Svelte', 'category' => 'Frontend Frameworks'],
            ['skill_name' => 'Node.js', 'category' => 'Backend Frameworks'],
            ['skill_name' => 'Express.js', 'category' => 'Backend Frameworks'],
            ['skill_name' => 'Laravel', 'category' => 'Backend Frameworks'],
            ['skill_name' => 'Spring Boot', 'category' => 'Backend Frameworks'],
            ['skill_name' => 'Django', 'category' => 'Backend Frameworks'],
            ['skill_name' => 'Ruby on Rails', 'category' => 'Backend Frameworks'],
            ['skill_name' => 'ASP.NET', 'category' => 'Backend Frameworks'],
            ['skill_name' => 'HTML', 'category' => 'Web Development'],
            ['skill_name' => 'CSS', 'category' => 'Web Development'],
            ['skill_name' => 'Responsive Design', 'category' => 'Web Development'],
            ['skill_name' => 'Sass/Less', 'category' => 'Web Development'],
            ['skill_name' => 'Bootstrap', 'category' => 'Web Development'],
            ['skill_name' => 'Tailwind CSS', 'category' => 'Web Development'],
            ['skill_name' => 'RESTful APIs', 'category' => 'API Development'],
            ['skill_name' => 'GraphQL', 'category' => 'API Development'],
            ['skill_name' => 'Microservices', 'category' => 'System Design'],
            ['skill_name' => 'Cloud Computing', 'category' => 'Cloud Platforms'],
            ['skill_name' => 'Amazon Web Services (AWS)', 'category' => 'Cloud Platforms'],
            ['skill_name' => 'Google Cloud Platform (GCP)', 'category' => 'Cloud Platforms'],
            ['skill_name' => 'Microsoft Azure', 'category' => 'Cloud Platforms'],
            ['skill_name' => 'Docker', 'category' => 'DevOps'],
            ['skill_name' => 'Kubernetes', 'category' => 'DevOps'],
            ['skill_name' => 'CI/CD', 'category' => 'DevOps'],
            ['skill_name' => 'Git', 'category' => 'Version Control'],
            ['skill_name' => 'GitHub', 'category' => 'Version Control'],
            ['skill_name' => 'GitLab', 'category' => 'Version Control'],
            ['skill_name' => 'Bitbucket', 'category' => 'Version Control'],
            ['skill_name' => 'Data Analysis', 'category' => 'Data Science'],
            ['skill_name' => 'Machine Learning', 'category' => 'Data Science'],
            ['skill_name' => 'Deep Learning', 'category' => 'Data Science'],
            ['skill_name' => 'Natural Language Processing (NLP)', 'category' => 'Data Science'],
            ['skill_name' => 'Computer Vision', 'category' => 'Data Science'],
            ['skill_name' => 'Pandas', 'category' => 'Data Science Libraries'],
            ['skill_name' => 'NumPy', 'category' => 'Data Science Libraries'],
            ['skill_name' => 'Scikit-learn', 'category' => 'Data Science Libraries'],
            ['skill_name' => 'TensorFlow', 'category' => 'Deep Learning Frameworks'],
            ['skill_name' => 'PyTorch', 'category' => 'Deep Learning Frameworks'],
            ['skill_name' => 'Power BI', 'category' => 'Business Intelligence'],
            ['skill_name' => 'Tableau', 'category' => 'Business Intelligence'],
            ['skill_name' => 'Excel (Advanced)', 'category' => 'Data Analysis Tools'],
            ['skill_name' => 'Cybersecurity', 'category' => 'Security'],
            ['skill_name' => 'Network Security', 'category' => 'Security'],
            ['skill_name' => 'Information Security', 'category' => 'Security'],
            ['skill_name' => 'Penetration Testing', 'category' => 'Security'],
            ['skill_name' => 'UI Design', 'category' => 'Design'],
            ['skill_name' => 'UX Design', 'category' => 'Design'],
            ['skill_name' => 'Figma', 'category' => 'Design Tools'],
            ['skill_name' => 'Adobe XD', 'category' => 'Design Tools'],
            ['skill_name' => 'Sketch', 'category' => 'Design Tools'],
            ['skill_name' => 'Adobe Photoshop', 'category' => 'Graphic Design'],
            ['skill_name' => 'Adobe Illustrator', 'category' => 'Graphic Design'],
            ['skill_name' => 'Video Editing', 'category' => 'Multimedia'],
            ['skill_name' => 'Adobe Premiere Pro', 'category' => 'Multimedia Tools'],
            ['skill_name' => 'Final Cut Pro', 'category' => 'Multimedia Tools'],
            ['skill_name' => 'Mobile App Development', 'category' => 'Mobile Development'],
            ['skill_name' => 'Android Development', 'category' => 'Mobile Development'],
            ['skill_name' => 'iOS Development', 'category' => 'Mobile Development'],
            ['skill_name' => 'React Native', 'category' => 'Cross-Platform Mobile'],
            ['skill_name' => 'Flutter', 'category' => 'Cross-Platform Mobile'],
            ['skill_name' => 'Game Development', 'category' => 'Game Development'],
            ['skill_name' => 'Unity', 'category' => 'Game Engines'],
            ['skill_name' => 'Unreal Engine', 'category' => 'Game Engines'],
            ['skill_name' => 'Robotics', 'category' => 'Emerging Technologies'],
            ['skill_name' => 'IoT (Internet of Things)', 'category' => 'Emerging Technologies'],
            ['skill_name' => 'Blockchain', 'category' => 'Emerging Technologies'],
            ['skill_name' => 'AR/VR Development', 'category' => 'Emerging Technologies'],
            ['skill_name' => 'ERP Systems', 'category' => 'Enterprise Software'],
            ['skill_name' => 'CRM Systems', 'category' => 'Enterprise Software'],
            ['skill_name' => 'SAP', 'category' => 'Enterprise Software'],
            ['skill_name' => 'Salesforce', 'category' => 'Enterprise Software'],
            ['skill_name' => 'E-commerce Platforms', 'category' => 'E-commerce'],
            ['skill_name' => 'Shopify', 'category' => 'E-commerce Platforms'],
            ['skill_name' => 'WordPress', 'category' => 'CMS'],
            ['skill_name' => 'Joomla', 'category' => 'CMS'],
            ['skill_name' => 'Drupal', 'category' => 'CMS'],
            ['skill_name' => 'SEO (Search Engine Optimization)', 'category' => 'Digital Marketing'],
            ['skill_name' => 'SEM (Search Engine Marketing)', 'category' => 'Digital Marketing'],
            ['skill_name' => 'Social Media Marketing', 'category' => 'Digital Marketing'],
            ['skill_name' => 'Content Marketing', 'category' => 'Digital Marketing'],
            ['skill_name' => 'Email Marketing', 'category' => 'Digital Marketing'],
            ['skill_name' => 'Google Analytics', 'category' => 'Digital Marketing Tools'],
            ['skill_name' => 'Google Ads', 'category' => 'Digital Marketing Tools'],
            ['skill_name' => 'Facebook Ads', 'category' => 'Digital Marketing Tools'],

            // --- Soft Skills ---
            ['skill_name' => 'Communication', 'category' => 'Interpersonal Skills'],
            ['skill_name' => 'Teamwork', 'category' => 'Interpersonal Skills'],
            ['skill_name' => 'Problem-Solving', 'category' => 'Cognitive Skills'],
            ['skill_name' => 'Adaptability', 'category' => 'Personal Attributes'],
            ['skill_name' => 'Leadership', 'category' => 'Leadership & Management'],
            ['skill_name' => 'Time Management', 'category' => 'Organizational Skills'],
            ['skill_name' => 'Critical Thinking', 'category' => 'Cognitive Skills'],
            ['skill_name' => 'Creativity', 'category' => 'Personal Attributes'],
            ['skill_name' => 'Emotional Intelligence', 'category' => 'Interpersonal Skills'],
            ['skill_name' => 'Conflict Resolution', 'category' => 'Interpersonal Skills'],
            ['skill_name' => 'Negotiation', 'category' => 'Business Skills'],
            ['skill_name' => 'Public Speaking', 'category' => 'Communication Skills'],
            ['skill_name' => 'Active Listening', 'category' => 'Communication Skills'],
            ['skill_name' => 'Presentation Skills', 'category' => 'Communication Skills'],
            ['skill_name' => 'Decision Making', 'category' => 'Cognitive Skills'],
            ['skill_name' => 'Attention to Detail', 'category' => 'Organizational Skills'],
            ['skill_name' => 'Work Ethic', 'category' => 'Personal Attributes'],
            ['skill_name' => 'Customer Service', 'category' => 'Customer Relations'],
            ['skill_name' => 'Sales', 'category' => 'Business Skills'],
            ['skill_name' => 'Marketing Strategy', 'category' => 'Business Skills'],
            ['skill_name' => 'Project Management', 'category' => 'Management'],
            ['skill_name' => 'Agile Methodologies', 'category' => 'Project Management Methodologies'],
            ['skill_name' => 'Scrum', 'category' => 'Project Management Methodologies'],
            ['skill_name' => 'Kanban', 'category' => 'Project Management Methodologies'],
            ['skill_name' => 'Mentoring', 'category' => 'Leadership & Management'],
            ['skill_name' => 'Coaching', 'category' => 'Leadership & Management'],
            ['skill_name' => 'Feedback Delivery', 'category' => 'Communication Skills'],
            ['skill_name' => 'Cross-functional Collaboration', 'category' => 'Teamwork'],
            ['skill_name' => 'Intercultural Communication', 'category' => 'Interpersonal Skills'],
            ['skill_name' => 'Networking', 'category' => 'Professional Development'],
            ['skill_name' => 'Research', 'category' => 'Cognitive Skills'],
            ['skill_name' => 'Data Entry', 'category' => 'Administrative'],
            ['skill_name' => 'Typing', 'category' => 'Administrative'],
            ['skill_name' => 'Event Planning', 'category' => 'Organizational Skills'],
            ['skill_name' => 'Budget Management', 'category' => 'Financial Skills'],
            ['skill_name' => 'Financial Analysis', 'category' => 'Financial Skills'],
            ['skill_name' => 'Accounting', 'category' => 'Financial Skills'],
            ['skill_name' => 'Bookkeeping', 'category' => 'Financial Skills'],
            ['skill_name' => 'Legal Research', 'category' => 'Legal Skills'],
            ['skill_name' => 'Compliance', 'category' => 'Regulatory & Compliance'],
            ['skill_name' => 'Regulatory Knowledge', 'category' => 'Regulatory & Compliance'],
            ['skill_name' => 'Patient Care', 'category' => 'Healthcare'],
            ['skill_name' => 'First Aid', 'category' => 'Healthcare'],
            ['skill_name' => 'CPR', 'category' => 'Healthcare'],
            ['skill_name' => 'Teaching', 'category' => 'Education'],
            ['skill_name' => 'Curriculum Development', 'category' => 'Education'],
            ['skill_name' => 'Training & Development', 'category' => 'HR & Training'],
            ['skill_name' => 'Recruitment', 'category' => 'HR & Training'],
            ['skill_name' => 'HR Management', 'category' => 'HR & Training'],
            ['skill_name' => 'Copywriting', 'category' => 'Content Creation'],
            ['skill_name' => 'Editing', 'category' => 'Content Creation'],
            ['skill_name' => 'Proofreading', 'category' => 'Content Creation'],
            ['skill_name' => 'Storytelling', 'category' => 'Content Creation'],
            ['skill_name' => 'Blogging', 'category' => 'Content Creation'],
            ['skill_name' => 'Journalism', 'category' => 'Media & Communication'],
            ['skill_name' => 'Photography', 'category' => 'Creative Arts'],
            ['skill_name' => 'Drawing', 'category' => 'Creative Arts'],
            ['skill_name' => 'Painting', 'category' => 'Creative Arts'],
            ['skill_name' => 'Sculpting', 'category' => 'Creative Arts'],
            ['skill_name' => 'Music Production', 'category' => 'Creative Arts'],
            ['skill_name' => 'Singing', 'category' => 'Creative Arts'],
            ['skill_name' => 'Playing Musical Instruments', 'category' => 'Creative Arts'],
            ['skill_name' => 'Performing Arts', 'category' => 'Creative Arts'],
            ['skill_name' => 'Fashion Design', 'category' => 'Creative Arts'],
            ['skill_name' => 'Interior Design', 'category' => 'Creative Arts'],
            ['skill_name' => 'Gardening', 'category' => 'Hobbies & Interests'],
            ['skill_name' => 'Cooking', 'category' => 'Hobbies & Interests'],
            ['skill_name' => 'Baking', 'category' => 'Hobbies & Interests'],
            ['skill_name' => 'Driving', 'category' => 'Practical Skills'],
            ['skill_name' => 'Vehicle Maintenance', 'category' => 'Practical Skills'],
            ['skill_name' => 'Carpentry', 'category' => 'Manual Skills'],
            ['skill_name' => 'Plumbing', 'category' => 'Manual Skills'],
            ['skill_name' => 'Electrical Work', 'category' => 'Manual Skills'],
            ['skill_name' => 'Welding', 'category' => 'Manual Skills'],
            ['skill_name' => 'Farming', 'category' => 'Agriculture'],
            ['skill_name' => 'Animal Care', 'category' => 'Animal Husbandry'],
            ['skill_name' => 'Pest Management', 'category' => 'Agriculture'],
            ['skill_name' => 'Food Safety', 'category' => 'Hospitality & Food Services'],
            ['skill_name' => 'Bartending', 'category' => 'Hospitality & Food Services'],
            ['skill_name' => 'Guest Services', 'category' => 'Hospitality & Food Services'],
            ['skill_name' => 'Tour Guiding', 'category' => 'Tourism'],
            ['skill_name' => 'Travel Planning', 'category' => 'Tourism'],
            ['skill_name' => 'Logistics', 'category' => 'Supply Chain'],
            ['skill_name' => 'Inventory Management', 'category' => 'Supply Chain'],
            ['skill_name' => 'Warehouse Operations', 'category' => 'Supply Chain'],
            ['skill_name' => 'Procurement', 'category' => 'Supply Chain'],
            ['skill_name' => 'Risk Management', 'category' => 'Business Operations'],
            ['skill_name' => 'Strategic Planning', 'category' => 'Business Operations'],
            ['skill_name' => 'Business Development', 'category' => 'Business Operations'],
            ['skill_name' => 'Market Research', 'category' => 'Business Operations'],
            ['skill_name' => 'Data Visualization', 'category' => 'Data Science'],
            ['skill_name' => 'Spreadsheet Software', 'category' => 'Office Tools'],
            ['skill_name' => 'Word Processing Software', 'category' => 'Office Tools'],
            ['skill_name' => 'Presentation Software', 'category' => 'Office Tools'],
            ['skill_name' => 'Virtual Assistance', 'category' => 'Administrative'],
            ['skill_name' => 'Report Writing', 'category' => 'Administrative'],
            ['skill_name' => 'Meeting Management', 'category' => 'Administrative'],
            ['skill_name' => 'Archiving', 'category' => 'Administrative'],
            ['skill_name' => 'Record Keeping', 'category' => 'Administrative'],
            ['skill_name' => 'Problem Diagnosis', 'category' => 'Technical Support'],
            ['skill_name' => 'Troubleshooting', 'category' => 'Technical Support'],
            ['skill_name' => 'Technical Documentation', 'category' => 'Technical Writing'],
            ['skill_name' => 'Grant Writing', 'category' => 'Non-Profit Management'],
            ['skill_name' => 'Fundraising', 'category' => 'Non-Profit Management'],
            ['skill_name' => 'Volunteer Management', 'category' => 'Non-Profit Management'],
            ['skill_name' => 'Community Outreach', 'category' => 'Community Engagement'],
            ['skill_name' => 'Social Work', 'category' => 'Social Services'],
            ['skill_name' => 'Counseling', 'category' => 'Social Services'],
            ['skill_name' => 'Child Care', 'category' => 'Social Services'],
            ['skill_name' => 'Elder Care', 'category' => 'Social Services'],
            ['skill_name' => 'Disability Support', 'category' => 'Social Services'],
            ['skill_name' => 'Crisis Intervention', 'category' => 'Social Services'],
            ['skill_name' => 'Environmental Conservation', 'category' => 'Environmental'],
            ['skill_name' => 'Sustainability Practices', 'category' => 'Environmental'],
            ['skill_name' => 'Waste Management', 'category' => 'Environmental'],
            ['skill_name' => 'Urban Planning', 'category' => 'Urban Development'],
            ['skill_name' => 'Civil Engineering', 'category' => 'Engineering'],
            ['skill_name' => 'Mechanical Engineering', 'category' => 'Engineering'],
            ['skill_name' => 'Electrical Engineering', 'category' => 'Engineering'],
            ['skill_name' => 'Chemical Engineering', 'category' => 'Engineering'],
            ['skill_name' => 'Biotechnology', 'category' => 'Science & Research'],
            ['skill_name' => 'Pharmacology', 'category' => 'Science & Research'],
            ['skill_name' => 'Genetics', 'category' => 'Science & Research'],
            ['skill_name' => 'Chemistry', 'category' => 'Science & Research'],
            ['skill_name' => 'Physics', 'category' => 'Science & Research'],
            ['skill_name' => 'Biology', 'category' => 'Science & Research'],
            ['skill_name' => 'Scientific Research', 'category' => 'Science & Research'],
            ['skill_name' => 'Laboratory Skills', 'category' => 'Science & Research'],
            ['skill_name' => 'Statistical Analysis', 'category' => 'Mathematics & Statistics'],
            ['skill_name' => 'Econometrics', 'category' => 'Economics'],
            ['skill_name' => 'Political Analysis', 'category' => 'Political Science'],
            ['skill_name' => 'Sociology', 'category' => 'Social Sciences'],
            ['skill_name' => 'Anthropology', 'category' => 'Social Sciences'],
            ['skill_name' => 'Psychology', 'category' => 'Social Sciences'],
            ['skill_name' => 'Geography', 'category' => 'Science & Research'],
            ['skill_name' => 'Cartography', 'category' => 'Geographic Information Systems (GIS)'],
            ['skill_name' => 'GIS (Geographic Information Systems)', 'category' => 'Geographic Information Systems (GIS)'],
            ['skill_name' => 'Remote Sensing', 'category' => 'Geographic Information Systems (GIS)'],

            // --- Languages (Commonly requested in Indonesia) ---
            ['skill_name' => 'Bahasa Indonesia', 'category' => 'Languages'],
            ['skill_name' => 'English', 'category' => 'Languages'],
            ['skill_name' => 'Mandarin', 'category' => 'Languages'],
            ['skill_name' => 'Japanese', 'category' => 'Languages'],
            ['skill_name' => 'Korean', 'category' => 'Languages'],
            ['skill_name' => 'Arabic', 'category' => 'Languages'],
            ['skill_name' => 'French', 'category' => 'Languages'],
            ['skill_name' => 'German', 'category' => 'Languages'],
            ['skill_name' => 'Spanish', 'category' => 'Languages'],
            ['skill_name' => 'Dutch', 'category' => 'Languages'],
            ['skill_name' => 'Vietnamese', 'category' => 'Languages'],
            ['skill_name' => 'Thai', 'category' => 'Languages'],
            ['skill_name' => 'Filipino', 'category' => 'Languages'],
            ['skill_name' => 'Portuguese', 'category' => 'Languages'],

            // --- Other Specific Software/Tools ---
            ['skill_name' => 'Jira', 'category' => 'Project Management Tools'],
            ['skill_name' => 'Trello', 'category' => 'Project Management Tools'],
            ['skill_name' => 'Asana', 'category' => 'Project Management Tools'],
            ['skill_name' => 'Slack', 'category' => 'Communication Tools'],
            ['skill_name' => 'Microsoft Teams', 'category' => 'Communication Tools'],
            ['skill_name' => 'Google Workspace', 'category' => 'Office Productivity'],
            ['skill_name' => 'Microsoft Office Suite', 'category' => 'Office Productivity'],
            ['skill_name' => 'SAP HANA', 'category' => 'Enterprise Software'],
            ['skill_name' => 'Oracle EBS', 'category' => 'Enterprise Software'],
            ['skill_name' => 'Zendesk', 'category' => 'Customer Service Software'],
            ['skill_name' => 'ServiceNow', 'category' => 'IT Service Management'],
            ['skill_name' => 'AutoCAD', 'category' => 'CAD Software'],
            ['skill_name' => 'SolidWorks', 'category' => 'CAD Software'],
            ['skill_name' => 'Revit', 'category' => 'BIM Software'],
            ['skill_name' => 'ArcGIS', 'category' => 'GIS Software'],
            ['skill_name' => 'QGIS', 'category' => 'GIS Software'],
            ['skill_name' => 'SPSS', 'category' => 'Statistical Software'],
            ['skill_name' => 'R (Programming Language)', 'category' => 'Statistical Software'],
            ['skill_name' => 'MATLAB', 'category' => 'Scientific Computing'],
            ['skill_name' => 'Simulink', 'category' => 'Scientific Computing'],
            ['skill_name' => 'Salesforce CRM', 'category' => 'CRM Software'],
            ['skill_name' => 'HubSpot', 'category' => 'Marketing & Sales Software'],
            ['skill_name' => 'Mailchimp', 'category' => 'Email Marketing Software'],
            ['skill_name' => 'Canva', 'category' => 'Design Tools'],
            ['skill_name' => 'GIMP', 'category' => 'Image Editing Software'],
            ['skill_name' => 'Blender', 'category' => '3D Modeling Software'],
            ['skill_name' => 'DaVinci Resolve', 'category' => 'Video Editing Software'],
            ['skill_name' => 'Audacity', 'category' => 'Audio Editing Software'],
            ['skill_name' => 'Packet Tracer', 'category' => 'Networking Tools'],
            ['skill_name' => 'Wireshark', 'category' => 'Networking Tools'],
            ['skill_name' => 'Nmap', 'category' => 'Security Tools'],
            ['skill_name' => 'Metasploit', 'category' => 'Security Tools'],
            ['skill_name' => 'Burp Suite', 'category' => 'Security Tools'],
            ['skill_name' => 'Selenium', 'category' => 'Test Automation'],
            ['skill_name' => 'JMeter', 'category' => 'Performance Testing'],
            ['skill_name' => 'Postman', 'category' => 'API Testing'],
            ['skill_name' => 'Insomnia', 'category' => 'API Testing'],
            ['skill_name' => 'Webpack', 'category' => 'Frontend Build Tools'],
            ['skill_name' => 'Babel', 'category' => 'JavaScript Transpilers'],
            ['skill_name' => 'ESLint', 'category' => 'Code Linting'],
            ['skill_name' => 'Prettier', 'category' => 'Code Formatting'],
            ['skill_name' => 'Jest', 'category' => 'JavaScript Testing'],
            ['skill_name' => 'Cypress', 'category' => 'End-to-End Testing'],
            ['skill_name' => 'Puppeteer', 'category' => 'Browser Automation'],
            ['skill_name' => 'Kafka', 'category' => 'Message Brokers'],
            ['skill_name' => 'RabbitMQ', 'category' => 'Message Brokers'],
            ['skill_name' => 'Redis', 'category' => 'Caching & Data Structures'],
            ['skill_name' => 'Memcached', 'category' => 'Caching'],
            ['skill_name' => 'Nginx', 'category' => 'Web Servers'],
            ['skill_name' => 'Apache HTTP Server', 'category' => 'Web Servers'],
            ['skill_name' => 'Ansible', 'category' => 'Configuration Management'],
            ['skill_name' => 'Chef', 'category' => 'Configuration Management'],
            ['skill_name' => 'Puppet', 'category' => 'Configuration Management'],
            ['skill_name' => 'Terraform', 'category' => 'Infrastructure as Code'],
            ['skill_name' => 'CloudFormation (AWS)', 'category' => 'Infrastructure as Code'],
            ['skill_name' => 'OAuth', 'category' => 'Authentication Protocols'],
            ['skill_name' => 'SAML', 'category' => 'Authentication Protocols'],
            ['skill_name' => 'LDAP', 'category' => 'Directory Services'],
            ['skill_name' => 'SSO (Single Sign-On)', 'category' => 'Authentication'],
            ['skill_name' => 'WebSockets', 'category' => 'Real-time Communication'],
            ['skill_name' => 'WebRTC', 'category' => 'Real-time Communication'],
            ['skill_name' => 'OAuth2', 'category' => 'Authentication & Authorization'],
            ['skill_name' => 'OpenID Connect', 'category' => 'Authentication & Authorization'],
            ['skill_name' => 'JWT (JSON Web Tokens)', 'category' => 'Authentication & Authorization'],
            ['skill_name' => 'Unit Testing', 'category' => 'Software Testing'],
            ['skill_name' => 'Integration Testing', 'category' => 'Software Testing'],
            ['skill_name' => 'End-to-End Testing', 'category' => 'Software Testing'],
            ['skill_name' => 'Performance Testing', 'category' => 'Software Testing'],
            ['skill_name' => 'Security Testing', 'category' => 'Software Testing'],
            ['skill_name' => 'Test-Driven Development (TDD)', 'category' => 'Software Development Methodologies'],
            ['skill_name' => 'Behavior-Driven Development (BDD)', 'category' => 'Software Development Methodologies'],
            ['skill_name' => 'Domain-Driven Design (DDD)', 'category' => 'Software Design Patterns'],
            ['skill_name' => 'Micro-Frontend', 'category' => 'Frontend Architecture'],
            ['skill_name' => 'Serverless Computing', 'category' => 'Cloud Architecture'],
            ['skill_name' => 'Edge Computing', 'category' => 'Cloud Architecture'],
            ['skill_name' => 'Quantum Computing', 'category' => 'Emerging Technologies'],
            ['skill_name' => 'Generative AI', 'category' => 'Artificial Intelligence'],
            ['skill_name' => 'Prompt Engineering', 'category' => 'Artificial Intelligence'],
            ['skill_name' => 'AI Ethics', 'category' => 'Artificial Intelligence'],
            ['skill_name' => 'Data Governance', 'category' => 'Data Management'],
            ['skill_name' => 'Data Warehousing', 'category' => 'Data Management'],
            ['skill_name' => 'ETL (Extract, Transform, Load)', 'category' => 'Data Management'],
            ['skill_name' => 'Business Process Automation', 'category' => 'Business Operations'],
            ['skill_name' => 'Robotic Process Automation (RPA)', 'category' => 'Business Operations'],
            ['skill_name' => 'Change Management', 'category' => 'Organizational Development'],
            ['skill_name' => 'Organizational Development', 'category' => 'Organizational Development'],
            ['skill_name' => 'Talent Acquisition', 'category' => 'HR & Training'],
            ['skill_name' => 'Employee Relations', 'category' => 'HR & Training'],
            ['skill_name' => 'Compensation & Benefits', 'category' => 'HR & Training'],
            ['skill_name' => 'Performance Management', 'category' => 'HR & Training'],
            ['skill_name' => 'Workforce Planning', 'category' => 'HR & Training'],
            ['skill_name' => 'Public Relations', 'category' => 'Marketing & Communications'],
            ['skill_name' => 'Brand Management', 'category' => 'Marketing & Communications'],
            ['skill_name' => 'Crisis Communication', 'category' => 'Marketing & Communications'],
            ['skill_name' => 'Media Relations', 'category' => 'Marketing & Communications'],
            ['skill_name' => 'Corporate Social Responsibility (CSR)', 'category' => 'Business Ethics'],
            ['skill_name' => 'Supply Chain Optimization', 'category' => 'Supply Chain'],
            ['skill_name' => 'Lean Manufacturing', 'category' => 'Operations Management'],
            ['skill_name' => 'Six Sigma', 'category' => 'Quality Management'],
            ['skill_name' => 'Quality Assurance (QA)', 'category' => 'Quality Management'],
            ['skill_name' => 'Software Quality Control', 'category' => 'Quality Management'],
            ['skill_name' => 'Clinical Research', 'category' => 'Healthcare & Research'],
            ['skill_name' => 'Medical Coding', 'category' => 'Healthcare Administration'],
            ['skill_name' => 'Medical Billing', 'category' => 'Healthcare Administration'],
            ['skill_name' => 'Electronic Health Records (EHR)', 'category' => 'Healthcare Technology'],
            ['skill_name' => 'Telemedicine', 'category' => 'Healthcare Technology'],
            ['skill_name' => 'Health Informatics', 'category' => 'Healthcare Technology'],
            ['skill_name' => 'Biostatistics', 'category' => 'Healthcare & Research'],
            ['skill_name' => 'Epidemiology', 'category' => 'Public Health'],
            ['skill_name' => 'Community Health', 'category' => 'Public Health'],
            ['skill_name' => 'Nutrition Science', 'category' => 'Health & Wellness'],
            ['skill_name' => 'Fitness Coaching', 'category' => 'Health & Wellness'],
            ['skill_name' => 'Personal Training', 'category' => 'Health & Wellness'],
            ['skill_name' => 'Yoga Instruction', 'category' => 'Health & Wellness'],
            ['skill_name' => 'Pilates Instruction', 'category' => 'Health & Wellness'],
            ['skill_name' => 'Mindfulness', 'category' => 'Health & Wellness'],
            ['skill_name' => 'Meditation', 'category' => 'Health & Wellness'],
            ['skill_name' => 'Counselling Psychology', 'category' => 'Psychology'],
            ['skill_name' => 'Clinical Psychology', 'category' => 'Psychology'],
            ['skill_name' => 'Cognitive Behavioral Therapy (CBT)', 'category' => 'Therapy'],
            ['skill_name' => 'Family Therapy', 'category' => 'Therapy'],
            ['skill_name' => 'Art Therapy', 'category' => 'Therapy'],
            ['skill_name' => 'Music Therapy', 'category' => 'Therapy'],
            ['skill_name' => 'Speech Therapy', 'category' => 'Therapy'],
            ['skill_name' => 'Physical Therapy', 'category' => 'Therapy'],
            ['skill_name' => 'Occupational Therapy', 'category' => 'Therapy'],
            ['skill_name' => 'Veterinary Medicine', 'category' => 'Animal Healthcare'],
            ['skill_name' => 'Animal Training', 'category' => 'Animal Care'],
            ['skill_name' => 'Zoology', 'category' => 'Science & Research'],
            ['skill_name' => 'Botany', 'category' => 'Science & Research'],
            ['skill_name' => 'Ecology', 'category' => 'Science & Research'],
            ['skill_name' => 'Oceanography', 'category' => 'Science & Research'],
            ['skill_name' => 'Astronomy', 'category' => 'Science & Research'],
            ['skill_name' => 'Geology', 'category' => 'Science & Research'],
            ['skill_name' => 'Meteorology', 'category' => 'Science & Research'],
            ['skill_name' => 'Archaeology', 'category' => 'Humanities'],
            ['skill_name' => 'History', 'category' => 'Humanities'],
            ['skill_name' => 'Philosophy', 'category' => 'Humanities'],
            ['skill_name' => 'Literature Analysis', 'category' => 'Humanities'],
            ['skill_name' => 'Linguistics', 'category' => 'Humanities'],
            ['skill_name' => 'Translation', 'category' => 'Languages'],
            ['skill_name' => 'Interpretation', 'category' => 'Languages'],
            ['skill_name' => 'Technical Translation', 'category' => 'Languages'],
            ['skill_name' => 'Localization', 'category' => 'Languages'],
            ['skill_name' => 'Voice Acting', 'category' => 'Creative Arts'],
            ['skill_name' => 'Scriptwriting', 'category' => 'Creative Arts'],
            ['skill_name' => 'Screenwriting', 'category' => 'Creative Arts'],
            ['skill_name' => 'Directing', 'category' => 'Film & Theatre'],
            ['skill_name' => 'Cinematography', 'category' => 'Film & Theatre'],
            ['skill_name' => 'Sound Design', 'category' => 'Film & Theatre'],
            ['skill_name' => 'Set Design', 'category' => 'Film & Theatre'],
            ['skill_name' => 'Costume Design', 'category' => 'Film & Theatre'],
            ['skill_name' => 'Makeup Artistry', 'category' => 'Creative Arts'],
            ['skill_name' => 'Hair Styling', 'category' => 'Creative Arts'],
            ['skill_name' => 'Photography Editing', 'category' => 'Creative Arts'],
            ['skill_name' => 'Retouching', 'category' => 'Creative Arts'],
            ['skill_name' => 'Illustration', 'category' => 'Creative Arts'],
            ['skill_name' => 'Animation', 'category' => 'Creative Arts'],
            ['skill_name' => '3D Modeling', 'category' => 'Creative Arts'],
            ['skill_name' => 'VFX (Visual Effects)', 'category' => 'Creative Arts'],
            ['skill_name' => 'AR/VR Content Creation', 'category' => 'Emerging Technologies'],
            ['skill_name' => 'Drone Piloting', 'category' => 'Technical Skills'],
            ['skill_name' => 'Data Forensics', 'category' => 'Cybersecurity'],
            ['skill_name' => 'Incident Response', 'category' => 'Cybersecurity'],
            ['skill_name' => 'Threat Intelligence', 'category' => 'Cybersecurity'],
            ['skill_name' => 'Security Auditing', 'category' => 'Cybersecurity'],
            ['skill_name' => 'Compliance Auditing', 'category' => 'Regulatory & Compliance'],
            ['skill_name' => 'Quality Control', 'category' => 'Manufacturing'],
            ['skill_name' => 'Product Development', 'category' => 'Business Operations'],
            ['skill_name' => 'Go-to-Market Strategy', 'category' => 'Marketing & Sales'],
            ['skill_name' => 'Competitive Analysis', 'category' => 'Business Operations'],
            ['skill_name' => 'Feasibility Studies', 'category' => 'Business Operations'],
            ['skill_name' => 'Financial Modeling', 'category' => 'Financial Skills'],
            ['skill_name' => 'Investment Management', 'category' => 'Financial Skills'],
            ['skill_name' => 'Risk Assessment', 'category' => 'Financial Skills'],
            ['skill_name' => 'Portfolio Management', 'category' => 'Financial Skills'],
            ['skill_name' => 'Mergers & Acquisitions (M&A)', 'category' => 'Financial Skills'],
            ['skill_name' => 'Corporate Finance', 'category' => 'Financial Skills'],
            ['skill_name' => 'Wealth Management', 'category' => 'Financial Skills'],
            ['skill_name' => 'Estate Planning', 'category' => 'Financial Skills'],
            ['skill_name' => 'Tax Preparation', 'category' => 'Financial Skills'],
            ['skill_name' => 'Auditing', 'category' => 'Financial Skills'],
            ['skill_name' => 'Bookkeeping Software (e.g., QuickBooks)', 'category' => 'Financial Tools'],
            ['skill_name' => 'Payment Processing', 'category' => 'E-commerce'],
            ['skill_name' => 'Fraud Detection', 'category' => 'Security'],
            ['skill_name' => 'Supply Chain Management Software', 'category' => 'Supply Chain Tools'],
            ['skill_name' => 'Fleet Management', 'category' => 'Logistics'],
            ['skill_name' => 'Warehouse Management System (WMS)', 'category' => 'Logistics'],
            ['skill_name' => 'Transportation Management System (TMS)', 'category' => 'Logistics'],
            ['skill_name' => 'Import/Export Regulations', 'category' => 'International Trade'],
            ['skill_name' => 'Customs Clearance', 'category' => 'International Trade'],
            ['skill_name' => 'International Business', 'category' => 'Business Operations'],
            ['skill_name' => 'Cross-Cultural Communication', 'category' => 'Interpersonal Skills'],
            ['skill_name' => 'Foreign Language Fluency', 'category' => 'Languages'], // General for any other language not listed
            ['skill_name' => 'Digital Forensics', 'category' => 'Cybersecurity'],
            ['skill_name' => 'Incident Response', 'category' => 'Cybersecurity'],
            ['skill_name' => 'Threat Hunting', 'category' => 'Cybersecurity'],
            ['skill_name' => 'Security Information and Event Management (SIEM)', 'category' => 'Cybersecurity Tools'],
            ['skill_name' => 'Intrusion Detection/Prevention Systems (IDPS)', 'category' => 'Cybersecurity Tools'],
            ['skill_name' => 'Firewall Management', 'category' => 'Cybersecurity Tools'],
            ['skill_name' => 'Endpoint Security', 'category' => 'Cybersecurity'],
            ['skill_name' => 'Identity and Access Management (IAM)', 'category' => 'Cybersecurity'],
            ['skill_name' => 'Security Awareness Training', 'category' => 'Cybersecurity'],
            ['skill_name' => 'Vulnerability Management', 'category' => 'Cybersecurity'],
            ['skill_name' => 'Disaster Recovery Planning', 'category' => 'IT Operations'],
            ['skill_name' => 'Business Continuity Planning', 'category' => 'IT Operations'],
            ['skill_name' => 'IT Support', 'category' => 'IT Operations'],
            ['skill_name' => 'Help Desk Support', 'category' => 'IT Operations'],
            ['skill_name' => 'Network Administration', 'category' => 'IT Operations'],
            ['skill_name' => 'System Administration', 'category' => 'IT Operations'],
            ['skill_name' => 'Database Administration', 'category' => 'IT Operations'],
            ['skill_name' => 'Web Server Administration', 'category' => 'IT Operations'],
            ['skill_name' => 'Virtualization (VMware, Hyper-V)', 'category' => 'IT Infrastructure'],
            ['skill_name' => 'Containerization (LXC, LXD)', 'category' => 'IT Infrastructure'],
            ['skill_name' => 'SAN/NAS Storage', 'category' => 'IT Infrastructure'],
            ['skill_name' => 'Backup and Recovery', 'category' => 'IT Operations'],
            ['skill_name' => 'Patch Management', 'category' => 'IT Operations'],
            ['skill_name' => 'Version Control Systems (SVN, Mercurial)', 'category' => 'Version Control'], // More specific VCs
            ['skill_name' => 'Integrated Development Environments (IDEs)', 'category' => 'Development Tools'],
            ['skill_name' => 'Debugging', 'category' => 'Software Development'],
            ['skill_name' => 'Code Review', 'category' => 'Software Development'],
            ['skill_name' => 'Refactoring', 'category' => 'Software Development'],
            ['skill_name' => 'Pair Programming', 'category' => 'Software Development'],
            ['skill_name' => 'Clean Code Principles', 'category' => 'Software Development'],
            ['skill_name' => 'Design Patterns', 'category' => 'Software Design'],
            ['skill_name' => 'Software Architecture', 'category' => 'Software Design'],
            ['skill_name' => 'Requirements Gathering', 'category' => 'Software Development Life Cycle'],
            ['skill_name' => 'Software Testing Lifecycle (STLC)', 'category' => 'Software Testing'],
            ['skill_name' => 'User Acceptance Testing (UAT)', 'category' => 'Software Testing'],
            ['skill_name' => 'Defect Tracking', 'category' => 'Software Testing'],
            ['skill_name' => 'Bug Reporting', 'category' => 'Software Testing'],
            ['skill_name' => 'Test Case Design', 'category' => 'Software Testing'],
            ['skill_name' => 'Automated Testing', 'category' => 'Software Testing'],
            ['skill_name' => 'Manual Testing', 'category' => 'Software Testing'],
            ['skill_name' => 'Performance Tuning', 'category' => 'Software Optimization'],
            ['skill_name' => 'Memory Management', 'category' => 'Software Optimization'],
            ['skill_name' => 'Concurrency', 'category' => 'Software Development'],
            ['skill_name' => 'Parallel Computing', 'category' => 'Software Development'],
            ['skill_name' => 'Distributed Systems', 'category' => 'System Design'],
            ['skill_name' => 'Load Balancing', 'category' => 'Network Infrastructure'],
            ['skill_name' => 'Firewalls', 'category' => 'Network Infrastructure'],
            ['skill_name' => 'Routers', 'category' => 'Network Infrastructure'],
            ['skill_name' => 'Switches', 'category' => 'Network Infrastructure'],
            ['skill_name' => 'VPN (Virtual Private Network)', 'category' => 'Network Security'],
            ['skill_name' => 'DNS (Domain Name System)', 'category' => 'Network Protocols'],
            ['skill_name' => 'HTTP/HTTPS', 'category' => 'Network Protocols'],
            ['skill_name' => 'TCP/IP', 'category' => 'Network Protocols'],
            ['skill_name' => 'RESTful Web Services', 'category' => 'API Development'],
            ['skill_name' => 'SOAP Web Services', 'category' => 'API Development'],
            ['skill_name' => 'Web Services Description Language (WSDL)', 'category' => 'API Development'],
            ['skill_name' => 'XML', 'category' => 'Data Formats'],
            ['skill_name' => 'JSON', 'category' => 'Data Formats'],
            ['skill_name' => 'YAML', 'category' => 'Data Formats'],
            ['skill_name' => 'CSV', 'category' => 'Data Formats'],
            ['skill_name' => 'Markdown', 'category' => 'Content Formatting'],
            ['skill_name' => 'LaTeX', 'category' => 'Academic Publishing'],
            ['skill_name' => 'GitOps', 'category' => 'DevOps'],
            ['skill_name' => 'SRE (Site Reliability Engineering)', 'category' => 'DevOps'],
            ['skill_name' => 'Observability', 'category' => 'DevOps'],
            ['skill_name' => 'Monitoring & Alerting', 'category' => 'DevOps'],
            ['skill_name' => 'Logging', 'category' => 'DevOps'],
            ['skill_name' => 'Service Mesh', 'category' => 'Cloud Native'],
            ['skill_name' => 'API Gateway', 'category' => 'Cloud Native'],
            ['skill_name' => 'Message Queues', 'category' => 'Distributed Systems'],
            ['skill_name' => 'Stream Processing', 'category' => 'Data Engineering'],
            ['skill_name' => 'Batch Processing', 'category' => 'Data Engineering'],
            ['skill_name' => 'Data Modeling', 'category' => 'Data Engineering'],
            ['skill_name' => 'Data Pipelining', 'category' => 'Data Engineering'],
            ['skill_name' => 'Big Data Technologies (Hadoop, Spark)', 'category' => 'Big Data'],
            ['skill_name' => 'Data Lakes', 'category' => 'Big Data'],
            ['skill_name' => 'Data Warehouses', 'category' => 'Big Data'],
            ['skill_name' => 'Data Marts', 'category' => 'Big Data'],
            ['skill_name' => 'Predictive Modeling', 'category' => 'Data Science'],
            ['skill_name' => 'Prescriptive Analytics', 'category' => 'Data Science'],
            ['skill_name' => 'Generative Adversarial Networks (GANs)', 'category' => 'Deep Learning'],
            ['skill_name' => 'Reinforcement Learning', 'category' => 'Machine Learning'],
            ['skill_name' => 'Transfer Learning', 'category' => 'Machine Learning'],
            ['skill_name' => 'Feature Engineering', 'category' => 'Machine Learning'],
            ['skill_name' => 'Model Deployment', 'category' => 'MLOps'],
            ['skill_name' => 'Model Monitoring', 'category' => 'MLOps'],
            ['skill_name' => 'A/B Testing', 'category' => 'Data Science'],
            ['skill_name' => 'Experiment Design', 'category' => 'Data Science'],
            ['skill_name' => 'Business Acumen', 'category' => 'Business Skills'],
            ['skill_name' => 'Strategic Thinking', 'category' => 'Business Skills'],
            ['skill_name' => 'Consulting', 'category' => 'Business Skills'],
            ['skill_name' => 'Client Management', 'category' => 'Business Skills'],
            ['skill_name' => 'Vendor Management', 'category' => 'Business Operations'],
            ['skill_name' => 'Contract Negotiation', 'category' => 'Business Operations'],
            ['skill_name' => 'Intellectual Property (IP)', 'category' => 'Legal & Business'],
            ['skill_name' => 'Patent Law', 'category' => 'Legal & Business'],
            ['skill_name' => 'Trademark Law', 'category' => 'Legal & Business'],
            ['skill_name' => 'Copyright Law', 'category' => 'Legal & Business'],
            ['skill_name' => 'Contract Law', 'category' => 'Legal & Business'],
            ['skill_name' => 'Corporate Law', 'category' => 'Legal & Business'],
            ['skill_name' => 'Environmental Law', 'category' => 'Legal & Business'],
            ['skill_name' => 'International Law', 'category' => 'Legal & Business'],
            ['skill_name' => 'Criminal Law', 'category' => 'Legal & Business'],
            ['skill_name' => 'Family Law', 'category' => 'Legal & Business'],
            ['skill_name' => 'Real Estate Law', 'category' => 'Legal & Business'],
            ['skill_name' => 'Employment Law', 'category' => 'Legal & Business'],
            ['skill_name' => 'Litigation', 'category' => 'Legal Skills'],
            ['skill_name' => 'Mediation', 'category' => 'Conflict Resolution'],
            ['skill_name' => 'Arbitration', 'category' => 'Conflict Resolution'],
            ['skill_name' => 'Legal Drafting', 'category' => 'Legal Skills'],
            ['skill_name' => 'Paralegal Support', 'category' => 'Legal Administration'],
            ['skill_name' => 'Courtroom Etiquette', 'category' => 'Legal Skills'],
            ['skill_name' => 'Client Counseling', 'category' => 'Legal Skills'],
            ['skill_name' => 'Investigation', 'category' => 'General Skills'],
            ['skill_name' => 'Report Writing (Legal)', 'category' => 'Legal Skills'],
            ['skill_name' => 'Research (General)', 'category' => 'General Skills'], // Broader research
            ['skill_name' => 'Fact-Checking', 'category' => 'General Skills'],
            ['skill_name' => 'Synthesizing Information', 'category' => 'Cognitive Skills'],
            ['skill_name' => 'Conceptual Thinking', 'category' => 'Cognitive Skills'],
            ['skill_name' => 'System Thinking', 'category' => 'Cognitive Skills'],
            ['skill_name' => 'Analytical Reasoning', 'category' => 'Cognitive Skills'],
            ['skill_name' => 'Logical Reasoning', 'category' => 'Cognitive Skills'],
            ['skill_name' => 'Inductive Reasoning', 'category' => 'Cognitive Skills'],
            ['skill_name' => 'Deductive Reasoning', 'category' => 'Cognitive Skills'],
            ['skill_name' => 'Abstract Thinking', 'category' => 'Cognitive Skills'],
            ['skill_name' => 'Pattern Recognition', 'category' => 'Cognitive Skills'],
            ['skill_name' => 'Visualization', 'category' => 'Cognitive Skills'],
            ['skill_name' => 'Hypothesis Testing', 'category' => 'Scientific Method'],
            ['skill_name' => 'Experimental Design', 'category' => 'Scientific Method'],
            ['skill_name' => 'Statistical Modeling', 'category' => 'Data Science'],
            ['skill_name' => 'Regression Analysis', 'category' => 'Data Science'],
            ['skill_name' => 'Classification', 'category' => 'Machine Learning'],
            ['skill_name' => 'Clustering', 'category' => 'Machine Learning'],
            ['skill_name' => 'Recommendation Systems', 'category' => 'Machine Learning'],
            ['skill_name' => 'Sentiment Analysis', 'category' => 'Natural Language Processing'],
            ['skill_name' => 'Speech Recognition', 'category' => 'Artificial Intelligence'],
            ['skill_name' => 'Image Recognition', 'category' => 'Computer Vision'],
            ['skill_name' => 'Facial Recognition', 'category' => 'Computer Vision'],
            ['skill_name' => 'Object Detection', 'category' => 'Computer Vision'],
            ['skill_name' => 'Semantic Segmentation', 'category' => 'Computer Vision'],
            ['skill_name' => 'Reinforcement Learning', 'category' => 'Artificial Intelligence'],
            ['skill_name' => 'Imitation Learning', 'category' => 'Artificial Intelligence'],
            ['skill_name' => 'Transfer Learning', 'category' => 'Artificial Intelligence'],
            ['skill_name' => 'Few-Shot Learning', 'category' => 'Artificial Intelligence'],
            ['skill_name' => 'Zero-Shot Learning', 'category' => 'Artificial Intelligence'],
            ['skill_name' => 'Federated Learning', 'category' => 'Artificial Intelligence'],
            ['skill_name' => 'Explainable AI (XAI)', 'category' => 'Artificial Intelligence'],
            ['skill_name' => 'Responsible AI', 'category' => 'Artificial Intelligence'],
            ['skill_name' => 'AI Model Governance', 'category' => 'Artificial Intelligence'],
            ['skill_name' => 'Cloud Security', 'category' => 'Cybersecurity'],
            ['skill_name' => 'Application Security (AppSec)', 'category' => 'Cybersecurity'],
            ['skill_name' => 'DevSecOps', 'category' => 'DevOps'],
            ['skill_name' => 'Zero Trust Architecture', 'category' => 'Cybersecurity'],
            ['skill_name' => 'Security Operations Center (SOC)', 'category' => 'Cybersecurity'],
            ['skill_name' => 'Threat Modeling', 'category' => 'Cybersecurity'],
            ['skill_name' => 'Security Information and Event Management (SIEM)', 'category' => 'Cybersecurity Tools'],
            ['skill_name' => 'Security Orchestration, Automation, and Response (SOAR)', 'category' => 'Cybersecurity Tools'],
            ['skill_name' => 'Extended Detection and Response (XDR)', 'category' => 'Cybersecurity Tools'],
            ['skill_name' => 'Digital Twin', 'category' => 'Emerging Technologies'],
            ['skill_name' => 'Metaverse Development', 'category' => 'Emerging Technologies'],
            ['skill_name' => 'Web3', 'category' => 'Emerging Technologies'],
            ['skill_name' => 'NFTs (Non-Fungible Tokens)', 'category' => 'Blockchain'],
            ['skill_name' => 'Smart Contracts', 'category' => 'Blockchain'],
            ['skill_name' => 'Decentralized Finance (DeFi)', 'category' => 'Blockchain'],
            ['skill_name' => 'Cryptocurrency Analysis', 'category' => 'Blockchain'],
            ['skill_name' => 'Tokenomics', 'category' => 'Blockchain'],
            ['skill_name' => 'Community Management', 'category' => 'Social Media'],
            ['skill_name' => 'Online Reputation Management', 'category' => 'Digital Marketing'],
            ['skill_name' => 'Influencer Marketing', 'category' => 'Digital Marketing'],
            ['skill_name' => 'Affiliate Marketing', 'category' => 'Digital Marketing'],
            ['skill_name' => 'Growth Hacking', 'category' => 'Marketing & Sales'],
            ['skill_name' => 'User Acquisition', 'category' => 'Marketing & Sales'],
            ['skill_name' => 'User Retention', 'category' => 'Marketing & Sales'],
            ['skill_name' => 'Conversion Rate Optimization (CRO)', 'category' => 'Digital Marketing'],
            ['skill_name' => 'A/B Testing (Marketing)', 'category' => 'Digital Marketing'],
            ['skill_name' => 'Web Analytics', 'category' => 'Digital Marketing'],
            ['skill_name' => 'Google Tag Manager', 'category' => 'Digital Marketing Tools'],
            ['skill_name' => 'CRM Administration', 'category' => 'Sales Operations'],
            ['skill_name' => 'Sales Enablement', 'category' => 'Sales Operations'],
            ['skill_name' => 'Sales Forecasting', 'category' => 'Sales & Business Development'],
            ['skill_name' => 'Account Management', 'category' => 'Sales & Customer Relations'],
            ['skill_name' => 'Key Account Management', 'category' => 'Sales & Customer Relations'],
            ['skill_name' => 'Client Relationship Management', 'category' => 'Customer Relations'],
            ['skill_name' => 'Technical Sales', 'category' => 'Sales'],
            ['skill_name' => 'Solution Selling', 'category' => 'Sales'],
            ['skill_name' => 'Channel Sales', 'category' => 'Sales'],
            ['skill_name' => 'Inside Sales', 'category' => 'Sales'],
            ['skill_name' => 'Field Sales', 'category' => 'Sales'],
            ['skill_name' => 'Retail Sales', 'category' => 'Sales'],
            ['skill_name' => 'Merchandising', 'category' => 'Retail Operations'],
            ['skill_name' => 'Store Operations Management', 'category' => 'Retail Operations'],
            ['skill_name' => 'Inventory Control', 'category' => 'Retail Operations'],
            ['skill_name' => 'Visual Merchandising', 'category' => 'Retail Operations'],
            ['skill_name' => 'Loss Prevention', 'category' => 'Retail Operations'],
            ['skill_name' => 'Supply Chain Analytics', 'category' => 'Supply Chain'],
            ['skill_name' => 'Logistics Optimization', 'category' => 'Logistics'],
            ['skill_name' => 'Procurement Strategy', 'category' => 'Supply Chain'],
            ['skill_name' => 'Contract Management', 'category' => 'Procurement'],
            ['skill_name' => 'Vendor Selection', 'category' => 'Procurement'],
            ['skill_name' => 'Spend Analysis', 'category' => 'Procurement'],
            ['skill_name' => 'Global Sourcing', 'category' => 'Procurement'],
            ['skill_name' => 'Customs Brokerage', 'category' => 'International Trade'],
            ['skill_name' => 'International Shipping', 'category' => 'Logistics'],
            ['skill_name' => 'Trade Compliance', 'category' => 'International Trade'],
            ['skill_name' => 'Export Control', 'category' => 'International Trade'],
            ['skill_name' => 'Geopolitics', 'category' => 'Global Affairs'],
            ['skill_name' => 'International Relations', 'category' => 'Global Affairs'],
            ['skill_name' => 'Economic Development', 'category' => 'Economics'],
            ['skill_name' => 'Public Policy Analysis', 'category' => 'Government & Public Policy'],
            ['skill_name' => 'Government Relations', 'category' => 'Government & Public Policy'],
            ['skill_name' => 'Lobbying', 'category' => 'Government & Public Policy'],
            ['skill_name' => 'Urban Planning Software (e.g., ArcGIS Urban)', 'category' => 'Urban Development Tools'],
            ['skill_name' => 'Environmental Impact Assessment (EIA)', 'category' => 'Environmental'],
            ['skill_name' => 'Sustainable Development Goals (SDGs)', 'category' => 'Sustainability'],
            ['skill_name' => 'Renewable Energy', 'category' => 'Environmental'],
            ['skill_name' => 'Energy Efficiency', 'category' => 'Environmental'],
            ['skill_name' => 'Waste Recycling', 'category' => 'Environmental'],
            ['skill_name' => 'Water Management', 'category' => 'Environmental'],
            ['skill_name' => 'Conservation Biology', 'category' => 'Environmental'],
            ['skill_name' => 'Ecosystem Management', 'category' => 'Environmental'],
            ['skill_name' => 'GIS Data Analysis', 'category' => 'Geographic Information Systems (GIS)'],
            ['skill_name' => 'Spatial Analysis', 'category' => 'Geographic Information Systems (GIS)'],
            ['skill_name' => 'Remote Sensing Data Processing', 'category' => 'Geographic Information Systems (GIS)'],
            ['skill_name' => 'Satellite Image Analysis', 'category' => 'Geographic Information Systems (GIS)'],
            ['skill_name' => 'Drone Data Processing', 'category' => 'Geographic Information Systems (GIS)'],
            ['skill_name' => 'Geospatial Modeling', 'category' => 'Geographic Information Systems (GIS)'],
            ['skill_name' => 'Cartographic Design', 'category' => 'Geographic Information Systems (GIS)'],
            ['skill_name' => 'Map Production', 'category' => 'Geographic Information Systems (GIS)'],
            ['skill_name' => 'Geostatistics', 'category' => 'Geographic Information Systems (GIS)'],
            ['skill_name' => 'Surveying', 'category' => 'Engineering'],
            ['skill_name' => 'Structural Analysis', 'category' => 'Engineering'],
            ['skill_name' => 'Fluid Dynamics', 'category' => 'Engineering'],
            ['skill_name' => 'Thermodynamics', 'category' => 'Engineering'],
            ['skill_name' => 'Control Systems', 'category' => 'Engineering'],
            ['skill_name' => 'Circuit Design', 'category' => 'Electrical Engineering'],
            ['skill_name' => 'Power Electronics', 'category' => 'Electrical Engineering'],
            ['skill_name' => 'Renewable Energy Systems', 'category' => 'Electrical Engineering'],
            ['skill_name' => 'Microcontrollers', 'category' => 'Electronics Engineering'],
            ['skill_name' => 'Embedded Systems', 'category' => 'Electronics Engineering'],
            ['skill_name' => 'Signal Processing', 'category' => 'Electrical Engineering'],
            ['skill_name' => 'Digital Logic Design', 'category' => 'Electrical Engineering'],
            ['skill_name' => 'VLSI Design', 'category' => 'Electrical Engineering'],
            ['skill_name' => 'Semiconductor Physics', 'category' => 'Physics'],
            ['skill_name' => 'Optics', 'category' => 'Physics'],
            ['skill_name' => 'Quantum Mechanics', 'category' => 'Physics'],
            ['skill_name' => 'Acoustics', 'category' => 'Physics'],
            ['skill_name' => 'Biochemistry', 'category' => 'Biology'],
            ['skill_name' => 'Molecular Biology', 'category' => 'Biology'],
            ['skill_name' => 'Cell Biology', 'category' => 'Biology'],
            ['skill_name' => 'Microbiology', 'category' => 'Biology'],
            ['skill_name' => 'Immunology', 'category' => 'Biology'],
            ['skill_name' => 'Neuroscience', 'category' => 'Biology'],
            ['skill_name' => 'Pharmacology', 'category' => 'Healthcare & Research'],
            ['skill_name' => 'Toxicology', 'category' => 'Healthcare & Research'],
            ['skill_name' => 'Drug Discovery', 'category' => 'Healthcare & Research'],
            ['skill_name' => 'Clinical Trials', 'category' => 'Healthcare & Research'],
            ['skill_name' => 'Regulatory Affairs (Pharma/Medical)', 'category' => 'Healthcare & Research'],
            ['skill_name' => 'Medical Devices', 'category' => 'Healthcare Technology'],
            ['skill_name' => 'Biomedical Engineering', 'category' => 'Engineering'],
            ['skill_name' => 'Rehabilitation Therapy', 'category' => 'Healthcare'],
            ['skill_name' => 'Diagnostic Imaging', 'category' => 'Healthcare'],
            ['skill_name' => 'Surgical Assistance', 'category' => 'Healthcare'],
            ['skill_name' => 'Anesthesia', 'category' => 'Healthcare'],
            ['skill_name' => 'Intensive Care', 'category' => 'Healthcare'],
            ['skill_name' => 'Emergency Medicine', 'category' => 'Healthcare'],
            ['skill_name' => 'Public Health Education', 'category' => 'Public Health'],
            ['skill_name' => 'Health Promotion', 'category' => 'Public Health'],
            ['skill_name' => 'Disease Prevention', 'category' => 'Public Health'],
            ['skill_name' => 'Health Policy', 'category' => 'Public Health'],
            ['skill_name' => 'Global Health', 'category' => 'Public Health'],
            ['skill_name' => 'Community Development', 'category' => 'Social Services'],
            ['skill_name' => 'Social Justice Advocacy', 'category' => 'Social Services'],
            ['skill_name' => 'Human Rights Advocacy', 'category' => 'Social Services'],
            ['skill_name' => 'Counseling Skills', 'category' => 'Social Services'],
            ['skill_name' => 'Psychological Assessment', 'category' => 'Psychology'],
            ['skill_name' => 'Therapeutic Modalities', 'category' => 'Therapy'],
            ['skill_name' => 'Recreational Therapy', 'category' => 'Therapy'],
            ['skill_name' => 'Art History', 'category' => 'Humanities'],
            ['skill_name' => 'Music Theory', 'category' => 'Creative Arts'],
            ['skill_name' => 'Dance', 'category' => 'Creative Arts'],
            ['skill_name' => 'Theatre Production', 'category' => 'Film & Theatre'],
            ['skill_name' => 'Costume Construction', 'category' => 'Film & Theatre'],
            ['skill_name' => 'Prop Making', 'category' => 'Film & Theatre'],
            ['skill_name' => 'Stage Management', 'category' => 'Film & Theatre'],
            ['skill_name' => 'Screen Printing', 'category' => 'Creative Arts'],
            ['skill_name' => 'Ceramics', 'category' => 'Creative Arts'],
            ['skill_name' => 'Jewelry Making', 'category' => 'Creative Arts'],
            ['skill_name' => 'Textile Design', 'category' => 'Creative Arts'],
            ['skill_name' => 'Weaving', 'category' => 'Creative Arts'],
            ['skill_name' => 'Knitting', 'category' => 'Creative Arts'],
            ['skill_name' => 'Sewing', 'category' => 'Creative Arts'],
            ['skill_name' => 'Pattern Making', 'category' => 'Fashion Design'],
            ['skill_name' => 'Garment Construction', 'category' => 'Fashion Design'],
            ['skill_name' => 'Fashion Styling', 'category' => 'Fashion'],
            ['skill_name' => 'Interior Decorating', 'category' => 'Interior Design'],
            ['skill_name' => 'Space Planning', 'category' => 'Interior Design'],
            ['skill_name' => 'Furniture Design', 'category' => 'Design'],
            ['skill_name' => 'Lighting Design', 'category' => 'Design'],
            ['skill_name' => 'Landscape Design', 'category' => 'Design'],
            ['skill_name' => 'Horticulture', 'category' => 'Agriculture'],
            ['skill_name' => 'Crop Management', 'category' => 'Agriculture'],
            ['skill_name' => 'Sustainable Agriculture', 'category' => 'Agriculture'],
            ['skill_name' => 'Precision Agriculture', 'category' => 'Agriculture'],
            ['skill_name' => 'Agricultural Engineering', 'category' => 'Engineering'],
            ['skill_name' => 'Food Processing', 'category' => 'Food Science'],
            ['skill_name' => 'Food Technology', 'category' => 'Food Science'],
            ['skill_name' => 'Culinary Arts', 'category' => 'Hospitality & Food Services'],
            ['skill_name' => 'Menu Planning', 'category' => 'Hospitality & Food Services'],
            ['skill_name' => 'Restaurant Management', 'category' => 'Hospitality & Food Services'],
            ['skill_name' => 'Hotel Management', 'category' => 'Hospitality & Food Services'],
            ['skill_name' => 'Tourism Management', 'category' => 'Tourism'],
            ['skill_name' => 'Leisure and Recreation Management', 'category' => 'Tourism'],
            ['skill_name' => 'Adventure Tourism', 'category' => 'Tourism'],
            ['skill_name' => 'Eco-Tourism', 'category' => 'Tourism'],
            ['skill_name' => 'Cultural Tourism', 'category' => 'Tourism'],
            ['skill_name' => 'Destination Marketing', 'category' => 'Tourism'],
            ['skill_name' => 'Tour Operations', 'category' => 'Tourism'],
            ['skill_name' => 'Travel Agency Operations', 'category' => 'Tourism'],
            ['skill_name' => 'Aviation Management', 'category' => 'Transportation'],
            ['skill_name' => 'Airport Operations', 'category' => 'Transportation'],
            ['skill_name' => 'Airline Operations', 'category' => 'Transportation'],
            ['skill_name' => 'Maritime Operations', 'category' => 'Transportation'],
            ['skill_name' => 'Shipping Management', 'category' => 'Transportation'],
            ['skill_name' => 'Railroad Operations', 'category' => 'Transportation'],
            ['skill_name' => 'Urban Transportation Planning', 'category' => 'Transportation'],
            ['skill_name' => 'Traffic Engineering', 'category' => 'Transportation'],
            ['skill_name' => 'Automotive Technology', 'category' => 'Technical Skills'],
            ['skill_name' => 'Motorcycle Repair', 'category' => 'Technical Skills'],
            ['skill_name' => 'Bicycle Repair', 'category' => 'Technical Skills'],
            ['skill_name' => 'Electronics Repair', 'category' => 'Technical Skills'],
            ['skill_name' => 'Home Appliance Repair', 'category' => 'Technical Skills'],
            ['skill_name' => 'HVAC (Heating, Ventilation, and Air Conditioning)', 'category' => 'Technical Skills'],
            ['skill_name' => 'Solar Panel Installation', 'category' => 'Technical Skills'],
            ['skill_name' => 'Wind Turbine Maintenance', 'category' => 'Technical Skills'],
            ['skill_name' => 'Carpentry (Advanced)', 'category' => 'Manual Skills'],
            ['skill_name' => 'Masonry', 'category' => 'Manual Skills'],
            ['skill_name' => 'Roofing', 'category' => 'Manual Skills'],
            ['skill_name' => 'Painting (Construction)', 'category' => 'Manual Skills'],
            ['skill_name' => 'Drywall Installation', 'category' => 'Manual Skills'],
            ['skill_name' => 'Flooring Installation', 'category' => 'Manual Skills'],
            ['skill_name' => 'Land Surveying', 'category' => 'Engineering'],
            ['skill_name' => 'Construction Management', 'category' => 'Construction'],
            ['skill_name' => 'Building Codes', 'category' => 'Construction'],
            ['skill_name' => 'Construction Safety', 'category' => 'Construction'],
            ['skill_name' => 'Blueprint Reading', 'category' => 'Construction'],
            ['skill_name' => 'Quantity Surveying', 'category' => 'Construction'],
            ['skill_name' => 'Estimating (Construction)', 'category' => 'Construction'],
            ['skill_name' => 'Heavy Equipment Operation', 'category' => 'Construction'],
            ['skill_name' => 'Welding (Advanced)', 'category' => 'Manual Skills'],
            ['skill_name' => 'Machining', 'category' => 'Manufacturing'],
            ['skill_name' => 'CNC Programming', 'category' => 'Manufacturing'],
            ['skill_name' => 'Robotics (Manufacturing)', 'category' => 'Manufacturing'],
            ['skill_name' => 'Quality Inspection', 'category' => 'Manufacturing'],
            ['skill_name' => 'Assembly Line Management', 'category' => 'Manufacturing'],
            ['skill_name' => 'Production Planning', 'category' => 'Manufacturing'],
            ['skill_name' => 'Inventory Optimization', 'category' => 'Supply Chain'],
            ['skill_name' => 'Warehouse Automation', 'category' => 'Logistics'],
            ['skill_name' => 'Distribution Management', 'category' => 'Logistics'],
            ['skill_name' => 'Returns Management', 'category' => 'Logistics'],
            ['skill_name' => 'Forecasting', 'category' => 'Business Operations'],
            ['skill_name' => 'Budgeting', 'category' => 'Financial Skills'],
            ['skill_name' => 'Financial Reporting', 'category' => 'Financial Skills'],
            ['skill_name' => 'Compliance (Financial)', 'category' => 'Financial Skills'],
            ['skill_name' => 'Internal Audit', 'category' => 'Financial Skills'],
            ['skill_name' => 'External Audit', 'category' => 'Financial Skills'],
            ['skill_name' => 'Tax Advisory', 'category' => 'Financial Skills'],
            ['skill_name' => 'Forensic Accounting', 'category' => 'Financial Skills'],
            ['skill_name' => 'Actuarial Science', 'category' => 'Financial Skills'],
            ['skill_name' => 'Insurance Underwriting', 'category' => 'Financial Skills'],
            ['skill_name' => 'Claims Processing', 'category' => 'Financial Skills'],
            ['skill_name' => 'Brokerage', 'category' => 'Financial Skills'],
            ['skill_name' => 'Hedge Funds', 'category' => 'Financial Skills'],
            ['skill_name' => 'Private Equity', 'category' => 'Financial Skills'],
            ['skill_name' => 'Venture Capital', 'category' => 'Financial Skills'],
            ['skill_name' => 'Investment Banking', 'category' => 'Financial Skills'],
            ['skill_name' => 'Retail Banking', 'category' => 'Financial Skills'],
            ['skill_name' => 'Corporate Banking', 'category' => 'Financial Skills'],
            ['skill_name' => 'Treasury Management', 'category' => 'Financial Skills'],
            ['skill_name' => 'Trade Finance', 'category' => 'Financial Skills'],
            ['skill_name' => 'Leasing', 'category' => 'Financial Skills'],
            ['skill_name' => 'Microfinance', 'category' => 'Financial Skills'],
            ['skill_name' => 'Wealth Planning', 'category' => 'Financial Skills'],
            ['skill_name' => 'Retirement Planning', 'category' => 'Financial Skills'],
            ['skill_name' => 'Estate Administration', 'category' => 'Legal & Financial'],
            ['skill_name' => 'Probate Law', 'category' => 'Legal & Financial'],
            ['skill_name' => 'Family Office Management', 'category' => 'Financial Skills'],
            ['skill_name' => 'Trust Administration', 'category' => 'Financial Skills'],
        ];

        foreach ($skills as $skill) {
            Skill::firstOrCreate(
                ['name' => $skill['skill_name']],
                ['category' => $skill['category']]
            );
        }
    }
}
